import type { DisplaySpec, ComparisonMessage } from "./types";

// Derived from data/server-specs.json display_specs array.
// show_in_calculator=NO rows (os) are excluded.
// cpu_architecture key renamed to cpu_passmark to match the DB column.
export const DISPLAY_SPECS: DisplaySpec[] = [
  { spec_key: "model_name",        display_label: "Server Model",           highlight_if_better: false, is_numeric: false, display_order: 1  },
  { spec_key: "max_cameras",       display_label: "Maximum Cameras",        highlight_if_better: true,  is_numeric: true,  display_order: 2  },
  { spec_key: "max_cameras_h265",  display_label: "Maximum H.265 Cameras",  highlight_if_better: true,  is_numeric: true,  display_order: 3  },
  { spec_key: "cpu_model",         display_label: "Processor",              highlight_if_better: true,  is_numeric: false, display_order: 4  },
  { spec_key: "cpu_cores_threads", display_label: "CPU Cores / Threads",    highlight_if_better: true,  is_numeric: false, display_order: 5  },
  { spec_key: "cpu_base_ghz",      display_label: "Base Clock Speed (GHz)", highlight_if_better: true,  is_numeric: true,  display_order: 6  },
  { spec_key: "cpu_passmark",      display_label: "CPU Passmark Score",     highlight_if_better: true,  is_numeric: true,  display_order: 7  },
  { spec_key: "ram_gb",            display_label: "Memory (GB)",            highlight_if_better: true,  is_numeric: true,  display_order: 8  },
  { spec_key: "storage_raw_tb",    display_label: "Raw Storage (TB)",       highlight_if_better: true,  is_numeric: true,  display_order: 9  },
  { spec_key: "network",           display_label: "Network Interfaces",     highlight_if_better: true,  is_numeric: false, display_order: 10 },
  { spec_key: "raid_support",      display_label: "RAID Support",           highlight_if_better: false, is_numeric: false, display_order: 11 },
  { spec_key: "warranty",          display_label: "Warranty",               highlight_if_better: false, is_numeric: false, display_order: 13 },
  { spec_key: "vms_certified",     display_label: "VMS Support",            highlight_if_better: true,  is_numeric: false, display_order: 14 },
  // Competitor-only (ADR 0073): the rebadged Dell/HP platform. Arxys rows have
  // no hw_platform value, so the Arxys column renders blank. No advantage badge.
  { spec_key: "hw_platform",       display_label: "Dell/HP Server Used",    highlight_if_better: false, is_numeric: false, display_order: 15 },
];

// Derived from data/server-specs.json messages array.
const RAW_MESSAGES: ComparisonMessage[] = [
  { message_key: "page_headline",      message_text: "Server Comparison Calculator" },
  { message_key: "page_subhead",       message_text: "See how a purpose-built Arxys VideoX server compares to your current VMS-branded appliance." },
  { message_key: "step1_label",        message_text: "Select your VMS platform" },
  { message_key: "step2_label",        message_text: "Select the server model you’ve been quoted" },
  { message_key: "price_disclosure",   message_text: "The Arxys MSRP shown is our published retail price — and it’s likely already lower than your discounted VMS-branded server price. Request your Security Partner discount to see how much more you save." },
  { message_key: "multiplier_label",   message_text: "What does this look like across a full deployment?" },
  { message_key: "multiplier_format",  message_text: "On a {n}-server deployment at this configuration, that’s ${total} in recovered project margin." },
  { message_key: "cta_headline",       message_text: "Want a formal quote with your partner pricing?" },
  { message_key: "cta_subtext",        message_text: "We’ll match this exact configuration and send you a quote within 24 hours." },
  { message_key: "cta_button",         message_text: "Get My Partner Quote" },
  { message_key: "pdf_button",         message_text: "Download This Comparison (PDF)" },
  { message_key: "pdf_footer",         message_text: "Comparison generated by Arxys VideoX Server Comparison Calculator. Pricing subject to change. Contact sales@arxys.com for a guaranteed quote." },
  { message_key: "hdd_callout",        message_text: "Arxys has secured Toshiba Enterprise HDD allocation (16TB, 20TB, 24TB) into 2027 — reducing supply chain delays." },
  { message_key: "second_source_note", message_text: "Many integrators start with Arxys as a second source on projects where hardware pricing or lead time is critical. No commitment to switch — just run one project and compare." },
  { message_key: "lead_time_callout",  message_text: "Arxys typically delivers in 3–4 weeks. VMS-branded servers currently quoting 4–16 weeks." },
];

export const MESSAGES: Record<string, string> = Object.fromEntries(
  RAW_MESSAGES.map((m) => [m.message_key, m.message_text]),
);
