-- Phase — Price versioning: products → append-only + current_products view
--
-- See docs/decisions/0076-append-only-price-versioning.md and the JOURNAL
-- entry for 2026-07-02.
--
-- Decouples "a portal/Excel price becomes effective" from "Pipedrive is
-- updated":
--   * public.products becomes APPEND-ONLY. Each price change is a NEW row for
--     that SKU with its own effective_date; prior rows are retained as the
--     historical record and never overwritten.
--   * public.current_products resolves, per SKU, the latest row whose
--     effective_date <= current_date. This is the single read-side resolution
--     point for the portal price book, the Excel export, and every other
--     reader — no cron, no flag flip, no background job.
--   * pushed_to_pipedrive_at records when (if ever) a specific price row was
--     pushed to Pipedrive by the manual `push-prices.ts --target=pipedrive`
--     step. NULL = never pushed by that step.
--
-- No foreign key references public.products(sku) (verified 2026-07-02:
--   - product_specs.id is its own text PK, joined to products.sku in-process,
--     no FK;
--   - competitor_products.arxys_match_id → product_specs(id), not products;
--   - the old uuid-id FKs were dropped in the Step 3+4 migration),
-- so dropping the sku primary key is safe. The whole file is one transaction —
-- any failure rolls back to the prior schema.

set check_function_bodies = off;

-- ---------------------------------------------------------------------------
-- 1. Surrogate primary key. `sku` can no longer be unique on its own once the
--    table holds multiple versioned rows per SKU. GENERATED BY DEFAULT (not
--    ALWAYS) so scripts/restore-tables.ts can replay dumped id values.
-- ---------------------------------------------------------------------------

alter table public.products
  add column id bigint generated by default as identity;

alter table public.products drop constraint products_pkey;            -- was primary key (sku)
alter table public.products add constraint products_pkey primary key (id);

-- ---------------------------------------------------------------------------
-- 2. Versioning columns.
--    effective_date backfills existing rows to 2026-05-05 (the price book's
--    published "Effective" date); future inserts default to the insert date.
-- ---------------------------------------------------------------------------

alter table public.products add column effective_date date;
update public.products set effective_date = date '2026-05-05' where effective_date is null;
alter table public.products
  alter column effective_date set not null,
  alter column effective_date set default current_date;

-- NULL = this row's price has never been pushed to Pipedrive by --target=pipedrive.
alter table public.products
  add column pushed_to_pipedrive_at timestamptz;

-- ---------------------------------------------------------------------------
-- 3. One price row per (sku, effective_date). Same-day corrections overwrite
--    that day's row (the pipeline upserts on this key); a different date
--    appends a new version.
-- ---------------------------------------------------------------------------

alter table public.products
  add constraint products_sku_effective_date_key unique (sku, effective_date);

-- Accelerates the DISTINCT ON (sku) ... ORDER BY effective_date DESC resolution.
create index products_sku_effective_idx
  on public.products (sku, effective_date desc);

-- ---------------------------------------------------------------------------
-- 4. current_products — the single "current price as of today" resolution
--    point. security_invoker = on so the base-table RLS policy on
--    public.products (active = true or is_admin) still governs which rows each
--    caller may see. Column list is identical to the pre-migration products
--    shape (plus id / effective_date / pushed_to_pipedrive_at) so readers only
--    change the table name, not their select lists.
-- ---------------------------------------------------------------------------

create view public.current_products
with (security_invoker = on) as
select distinct on (sku)
  id,
  sku,
  product_name,
  msrp,
  price_type,
  product_group,
  sort_order,
  active,
  max_cameras,
  max_storage_tb,
  effective_date,
  pushed_to_pipedrive_at,
  updated_at
from public.products
where effective_date <= current_date
order by sku, effective_date desc, id desc;

grant select on public.current_products to authenticated;
